title: OSU copy cop
description: Stay within the lines of the OSU style guide.

baseurl: /osu-copy-cop
markdown: kramdown
sass:
  style: :compressed

author: 
  name: John McQueen
  email: 
  uri: 

angularjs: 1.4.8

